Convert hydrate.js to ES5 for IE11 compatibility (closes #77)
hashicorp/next-mdx-remote pull request #79
Opened 2020-12-22 12:26 UTC by cknitt

2020-12-22 12:26 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/next-mdx-remote?pullRequest=79)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/next-mdx-remote?pullRequest=79)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/next-mdx-remote?pullRequest=79).</sub>

2020-12-22 16:59 UTC, jescalan requested changes
Thank you for this good work! There are still a few spots where IE11 would fail. Did you test this in IE yet?

2020-12-22 16:59 UTC, jescalan commented on hydrate.js
> +      var values = Object.values(fullScope)
IE11 doesn't support `Object.values` sadly: https://caniuse.com/object-values

2020-12-22 16:59 UTC, jescalan commented on hydrate.js
> +      var hydrateFn = Reflect.construct(
Not supported by IE11: https://caniuse.com/mdn-javascript_builtins_reflect

2020-12-22 17:21 UTC, cknitt commented
Yes, I tested this successfully in IE11.

The unsupported functions are automatically polyfilled by Next.js, see https://nextjs.org/docs/basic-features/supported-browsers-features#polyfills (which unfortunately does not list the exact polyfill that are applied, but `Object.assign` and `Reflect.construct` are definitely among them).

2020-12-22 17:30 UTC, jescalan commented
Oh that's great! hadn't considered this. Thank you! I'll try to get this shipped out soon 😀

2020-12-22 17:46 UTC, cknitt commented
Great, thanks a lot! 😀

2020-12-23 21:38 UTC, jescalan approved these changes

2020-12-23 22:21 UTC, merged